global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: [ '46.253.143.250:9113']
    metrics_path: '/metrics'
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ '46.253.143.250:9100']
    
